// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SawyerAir.Models;

namespace SawyerAir.Migrations
{
    [DbContext(typeof(FlightsContext))]
    [Migration("20210406214213_Migration0")]
    partial class Migration0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SawyerAir.Models.Line", b =>
                {
                    b.Property<int>("Id_Line")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Line");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("SawyerAir.Models.Plane", b =>
                {
                    b.Property<int>("Id_Plane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Line")
                        .HasColumnType("int");

                    b.Property<int?>("LineId_Line")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Plane");

                    b.HasIndex("LineId_Line");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("SawyerAir.Models.Plane", b =>
                {
                    b.HasOne("SawyerAir.Models.Line", "Line")
                        .WithMany("Planes")
                        .HasForeignKey("LineId_Line");
                });
#pragma warning restore 612, 618
        }
    }
}
